### ISSUE TITLE
Master Issue

### ISSUE THREAD

**Issue by hojaeklee** [hojaeklee/SfM_3D_Reconstruction#6]
- [ ] Sphinx Documentation using restructured text 
- [ ] Look & share restructured text (reST)
- [ ] PyTest: writing unit-testing (Search for "The Art of Unit Testing" 2nd. edition)
- [ ] Write `minimum_spanning_tree`
- [ ] Write `bundle_adjustment`
- [ ] Compatibility with later version(s) of OpenCV
- [ ] setup.py
- [ ] requirements.txt or environment.yml 
- [ ] Register to PyPI

- Badges:
- [ ] Travis Continuous Integration
- [ ] Codecov
- [ ] Pyup
- [ ] Documentation (readthedocs.org)
- [ ] Downloads
